# Generated by Django 4.2.11 on 2025-03-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('liquidado', 'Liquidado')], default='pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=50)),
                ('amount_reals', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('is_urgent', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('market_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DollarPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_dollars', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_received', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('beneficiario', 'Beneficiário'), ('antecipado', 'Antecipado')], max_length=15)),
                ('related_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='receipts/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemittanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('em_processamento', 'Em Processamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('total_amount_reals', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expected_dollars', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dollars_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='SellTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_dollars_sold', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('transfer_type', models.CharField(choices=[('wire', 'Wire Transfer'), ('usdt', 'USDT')], max_length=10)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_to_receive', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
