# Generated by Django 4.2.11 on 2025-03-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selltransaction',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selltransaction',
            name='daily_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.dailyrate'),
        ),
        migrations.AddField(
            model_name='remittancerequest',
            name='daily_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.dailyrate'),
        ),
        migrations.AddField(
            model_name='remittancerequest',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'role': 'varejista'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dollarpurchase',
            name='remittance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='operacoes.remittancerequest'),
        ),
        migrations.AddField(
            model_name='beneficiarypayment',
            name='remittance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='operacoes.remittancerequest'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
