# Generated by Django 4.2.11 on 2025-03-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='beneficiarypayment',
            name='agency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='beneficiarypayment',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='beneficiarypayment',
            name='pix_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiarypayment',
            name='pix_key_type',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('email', 'Email'), ('phone', 'Telefone'), ('random', 'Chave Aleatória')], max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiarypayment',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiarypayment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacoes.bank'),
        ),
    ]
