# Generated by Django 4.2.11 on 2025-03-21 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacoes', '0003_bank_beneficiarypayment_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarypayment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='remittancerequest',
            name='payer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'atacadista'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_to_process', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficiarypayment',
            name='remittance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='operacoes.remittancerequest'),
        ),
        migrations.AlterField(
            model_name='beneficiarypayment',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('invalido', 'Inválido')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='remittancerequest',
            name='retailer',
            field=models.ForeignKey(limit_choices_to={'role': 'varejista'}, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to=settings.AUTH_USER_MODEL),
        ),
    ]
