# Generated by Django 4.2.11 on 2025-03-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_beneficiarypayment_reason_remittancerequest_payer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarypayment',
            name='remittance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='operacoes.remittancerequest'),
        ),
    ]
